version: '3'

networks:
  app-network:
    driver: bridge

volumes:
  migrations:

services:
  db:
    image: postgres:14.10-alpine3.19
    container_name: db
    networks:
      - app-network
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASS}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '${DB_PORT}:5432'

  backend:
    restart: unless-stopped
    container_name: backend
    networks:
      - app-network
    env_file:
      - .env
    build:
      args:
        MODULE: backend
        MODE: ${MODE}
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./logs:/logs
    depends_on:
      - db
    ports:
      - 8001:8001

  migration_job:
    networks:
      - app-network
    build:
      context: .
      dockerfile: migrate.Dockerfile
    env_file: .env
    depends_on:
      - db